### ISSUE TITLE
The participant `recruiter_id` should be included in the player state

### ISSUE THREAD

**Issue by alecpm** [Dallinger/Griduniverse#192]
The serialized grid state includes a variety of information about the player (via `Player.serialize()`), but it does not include information about whether the player is a bot or a human. Including the `recruiter_id` in the player state (or some related value) would allow game logic and post-experiment analysis to make distinguish between bot and human participants.

Related to Dallinger/Dallinger#1367

**Comment by jessesnyder** [comment]
Merged - closing.
