### ISSUE TITLE
Upgrade numpy

### ISSUE THREAD

**Issue by vlall** [Dallinger/Griduniverse#220]
This is the same issue on Dallinger https://github.com/Dallinger/Dallinger/issues/1575, an installation failure is encountered when installing the requirements files on Python 3.7.X. The fix is a simple version bump of numpy to `1.15.4` when running Python 3.7.x.

**Comment by witekdev** [comment]
Looks like this was fixed a few days ago - https://github.com/Dallinger/Griduniverse/commit/e213a5b9e6f69fcad4ac33f3398b5b81e3aad0d1
