### ISSUE TITLE
Figure out what on earth happened to the maze-building algorithm

### ISSUE THREAD

**Issue by suchow** [Dallinger/Griduniverse#90]
```
columns = 100
rows = 100
walls_contiguity = 1.0
walls_density = 0.85
```
![image](https://user-images.githubusercontent.com/613981/27494669-ddd472aa-581c-11e7-9589-281310ef1aca.png)

**Comment by vlall** [comment]
This has been fixed see:
https://github.com/Dallinger/Griduniverse/pull/156
https://github.com/Dallinger/Griduniverse/pull/157
https://github.com/Dallinger/Griduniverse/pull/155
